name: '2.26'
favicon: null
layout_spectrum: 0.91902
typography_spectrum: 0.77954
title: February 26th Test Site
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#be433c'
    - '#34231c'
    - '#9a2925'
    - '#63221a'
    - '#423733'
  brandStrength: 0.875
  lightness: 0.9420471410267055
  saturation: 0.5625
  rhythmicContrast: 0.21958711557090282
purpose: []
